variables:
  DOCKER_DRIVER: overlay2

stages:
    - lint
    - build
    - test
    - release
    - deploy

lint flake8:
  stage: lint
  image: python:3.11.0-slim
  script:
    - flake8 .
  before_script:
    - pip install -r requirements-dev.txt

lint black:
  stage: lint
  image: python:3.11.0-slim
  script:
    - black --check .
  before_script:
    - pip install -r requirements-dev.txt

build webapp:
    stage: build
    except:
        - tags
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker build -t $docker_hub_login/simple_web_app:$CI_COMMIT_SHA .

test webapp:
    stage: test
    except:
        - tags
    image: python:3.11.0-slim
    script:
        - coverage run -m pytest
        - coverage report
        - coverage xml
    before_script:
      - pip install -r requirements-dev.txt
      - cd simple_web_app
    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    artifacts:
        paths:
            - coverage.xml
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml

release webapp:
    stage: release
    except:
        - tags
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker tag $docker_hub_login/simple_web_app:$CI_COMMIT_SHA $docker_hub_login/simple_web_app:latest
        - docker push $docker_hub_login/simple_web_app:$CI_COMMIT_SHA
        - docker push $docker_hub_login/simple_web_app:latest
    before_script:
        - docker login -u=$docker_hub_login -p=$docker_hub_token

deploy production:
    stage: deploy
    image: curlimages/curl:7.86.0 sh
    when: manual
    before_script:
        - curl -fsSL https://get.deta.dev/cli.sh | sh
        - cd simple_web_app
    only:
        - main
    script:
        - ~/.deta/bin/deta deploy
