variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

stages:
    - linting
    - build
    - test
    - release

lint flake8:
  stage: linting
  image: python:3.11.0-slim
  script:
    - flake8 .
  before_script:
    - pip install -r requirements.txt
    - cd simple_web_app

build webapp:
    stage: build
    except:
        - tags
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker build -t $docker_hub_login/simple_web_app:$CI_COMMIT_SHA .

test webapp:
    stage: test
    except:
        - tags
    image: python:3.11.0-slim
#    services: # start a real database for your service like postgres
#        - postgres:11.3-alpine
    script:
        - coverage run --include='./*' manage.py test
        - coverage report
        - coverage xml
    before_script:
      - pip install -r requirements.txt
      - cd simple_web_app
      - export DEBUG=True
    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    artifacts:
        paths:
            - coverage.xml
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml

release webapp:
    stage: release
    except:
        - tags
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker push $docker_hub_login/simple_web_app:$CI_COMMIT_SHA
    before_script:
        - docker login -u=$docker_hub_login -p=$docker_hub_token
