stages:
    - build

build webapp:
    stage: build
    except:
        - tags
    image: docker:stable
    services:
        - docker:dind
    script:
        - cd api
        - docker login -u=$docker_hub_login -p=$docker_hub_token
        - docker build -t $docker_hub_login/simple_web_app:$CI_COMMIT_SHA .
        - docker push $docker_hub_login/simple_web_app:$CI_COMMIT_SHA
