name: 'coverage'
on:
  pull_request:
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Testing
      run: |
        poetry run coverage run -m pytest
        poetry run coverage report
        poetry run coverage xml
    - name: Get Cover 
      uses: orgoro/coverage@v3
      with:
        coverageFile: coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}

